# Basic information
name:               "Xavier Teruel"

# Author information
author:
  name:             "Xavier Teruel"
  facebook:         xteruel
  twitter:          xavierteruel
  github:           xteruel
  linkedin:         xteruel
  email:            your-id@your-email.com

# Google-analytics
#google-analytics:
#  id:               ""

# URL
url:                "https://xteruel.github.io"
baseurl:            ""
#baseurl:            "/home/xteruel/Documents/web/xteruel.github.io/_site"

# Pagination
paginate:           5
paginate_path:      /archive/page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "bio"
    url:            "/"
#  - name:           "cv"
#    url:            "/cv"
  - name:           "archive"
    url:            "/archive"
#  - name:           "blog"
#    url:            "/blog"
  - name:           "publications"
    url:            "/publications"
  - name:           "teaching"
    url:            "/teaching"
  - name:           "tags"
    url:            "/tags"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Gems
gems: [jekyll-paginate]
