# Basic information
name:               "Xavier Teruel"

# Author information
author:
  name:             "Xavier Teruel"
  facebook:         xteruel
  twitter:          xavierteruel
  github:           xteruel
  linkedin:         xteruel
  orcid:            0000-0001-5181-7545
  research-gate:    70754315_Xavier_Teruel
  researcher-id:    H-8869-2015
  google-scholar:   FrhXHesAAAAJ
  instagram:        xteruel
  scopus:           25522775800

# Google-analytics
#google-analytics:
#  id:               ""

# URL
url:                "http://xavierteruel.com"
baseurl:            ""
#baseurl:            "/home/xteruel/Documents/web/xteruel.github.io/_site"

# Permalink
permalink: /:categories/:year/:month/:day/:title/

# Pagination
paginate:           10
paginate_path:      /archive/page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "home"
    url:            "/"
  - name:           "hpc"
    url:            "/hpc/"
  - name:           "archive"
    url:            "/archive/"
  - name:           "projects"
    url:            "/hpc/projects/"
  - name:           "publications"
    url:            "/hpc/publications/"
  - name:           "talks"
    url:            "/hpc/talks/"
  - name:           "tags"
    url:            "/tags/"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Other directories
include: [_pages]

# Gems
gems: [jekyll-paginate]
