# Basic information
name:               "Xavier Teruel"

# Author information
author:
  name:             your-name
  facebook:         your-id
  twitter:          your-id
  github:           your-id
  linkedin:         your-id
  medium:           your-id
  tumblr:           your-id
  email:            your-id@your-email.com

# Google-analytics
google-analytics:
  id:               ""

# URL
url:                "https://xteruel.github.io"
baseurl:            ""

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
