# Basic information
name:               "Xavier Teruel"

# Author information
author:
  name:             "Xavier Teruel"
  facebook:         xteruel
  twitter:          xavierteruel
  github:           xteruel
  linkedin:         xteruel
  email:            your-id@your-email.com

# Google-analytics
#google-analytics:
#  id:               ""

# URL
url:                "https://xteruel.github.io"
baseurl:            ""

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "Archive"
    url:            "/archive"
  - name:           "Publications"
    url:            "/publications"
  - name:           "Tags"
    url:            "/tags"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed
